spring:
  application:
    name: FeastOrd
  datasource:
    url: jdbc:postgresql://localhost:5432/feastord
    username: postgres
    password: 183020
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true