spring:

  datasource:

    url: jdbc:postgresql://localhost:5432/FeastOrd_db
    # Nom d'utilisateur et mot de passe de la base de donn√©es
    username: anonyme
    password: anonyme
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    show-sql: true
